# Generated by Django 3.2.4 on 2021-07-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_driverprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='ip_address',
            field=models.CharField(default='127.0.0.1', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='working',
            field=models.BooleanField(default=False),
        ),
    ]
