# Generated by Django 3.2.4 on 2021-07-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210726_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='phone_number',
            field=models.CharField(default='Unknown', max_length=15),
            preserve_default=False,
        ),
    ]
