# Generated by Django 3.2.4 on 2021-07-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_driverprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile-images/img/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='thumbnail_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile-images/thumbnails/'),
        ),
    ]
