# Generated by Django 3.2.4 on 2021-07-27 02:32

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210726_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='thumbnail_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=(200, 200), upload_to='profile-images/thumbnails/'),
        ),
    ]
