# Generated by Django 3.2.4 on 2021-07-26 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rating', models.PositiveIntegerField(choices=[(0, 'Unrated'), (1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=0)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DestinationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ability', models.PositiveIntegerField(choices=[(0, 'Unrated'), (1, 'Level One'), (2, 'Level Two'), (3, 'Level Three'), (4, 'Level Four'), (5, 'Level Five')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.PositiveIntegerField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.destination')),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='destination_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.destinationtype'),
        ),
    ]
