# Generated by Django 3.2.4 on 2021-07-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='address',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
    ]
