# Generated by Django 3.2.4 on 2021-07-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_destination_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(help_text='Location name e.g General Hospital, Kubwa', max_length=200),
        ),
        migrations.AlterField(
            model_name='destinationtype',
            name='ability',
            field=models.PositiveIntegerField(choices=[(0, 'Unrated'), (1, 'Level One'), (2, 'Level Two'), (3, 'Level Three'), (4, 'Level Four'), (5, 'Level Five')], default=0, help_text='e.g Hospital = 5, Pharmacy = 1'),
        ),
    ]
