# Generated by Django 3.2.4 on 2021-07-25 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0002_transport_driver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplies',
            options={'verbose_name_plural': 'Supplies'},
        ),
        migrations.RenameField(
            model_name='supplies',
            old_name='desription',
            new_name='description',
        ),
    ]
