# Generated by Django 3.2.4 on 2021-07-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0003_auto_20210726_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='supplies',
            field=models.ManyToManyField(blank=True, related_name='transports', to='transports.Supplies'),
        ),
    ]
